### PR TITLE
stream-engine/store: fix zero record header

### LINKED ISSUE #643: test log::tests::log_writer_and_reader_randomly ... FAILED
### Search before asking

- [X] I had searched in the [issues](https://github.com/engula/engula/issues) and found no similar issues.

### Minimal reproduce step

Run:

```sh
cargo test -p stream-engine-store -- --nocapture log::tests::log_writer_and_reader_randomly
```

### What did you expect to see?

```sh
test log::engine::tests::log_writer_and_reader_randomly... ok
```

### What did you see instead?

```
test log::tests::log_writer_and_reader_randomly ... FAILED

failures:

---- log::tests::log_writer_and_reader_randomly stdout ----
thread 'log::tests::log_writer_and_reader_randomly' panicked at 'assertion failed: `(left == right)`
  left: `254375`,
 right: `254376`', src/stream-engine/store/src/log/mod.rs:209:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    log::tests::log_writer_and_reader_randomly

test result: FAILED.
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by w41ter**
This PR closes #643.

### CODE REVIEW

File: src/stream-engine/store/src/log/mod.rs [hunk 1]
```diff
@@ -169,18 +169,25 @@ mod tests {
 
     #[test]
     fn log_writer_and_reader_randomly() -> Result<()> {
+        let issue_643 = 10859556100552729381;
+        let rand_seed = rand::thread_rng().gen::<u64>();
+        log_writer_and_reader_randomly_with_seed(issue_643)?;
+        log_writer_and_reader_randomly_with_seed(rand_seed)
```
Comment (tisonkun) [inline src/stream-engine/store/src/log/mod.rs:175]:
```suggestion
        let seed_causes_issue_643 = 10859556100552729381;
        let rand_seed = rand::thread_rng().gen::<u64>();
        log_writer_and_reader_randomly_with_seed(seed_causes_issue_643)?;
        log_writer_and_reader_randomly_with_seed(rand_seed)
```

**Review by tisonkun — APPROVED** [review]
LGTM. Minor suggestions inline.
